=== melli79/melli79.github.io/games/relatives/relatives.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "file://relatives.schema.json",
  "title": "Relative",
  "description": "A tree of relatives",
  "$dynamicAnchor": "relative",
  "type": "object",
  "properties": {
    "givenNames": {
      "description": "The given names of a relative",
      "type": "array",
      "item": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "gender": {
      "description": "The preferred gender of the person.  The gender will also decide whether the person is addressed a father/mother, brother/sister, ...",
      "type": "string",
      "enum": [ "male", "female", "other" ]
    },
    "birthday": {
      "description": "The known parts of the birthday",
      "type": "object",
      "properties": {
        "year": {
          "type": "integer",
          "minimum": 1600,
          "maximum": 2100
        },
        "month": {
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "day": {
          "type": "integer",
          "minimum": 1,
          "maximum": 31
        }
      }
    },
    "familyName": {
      "description": "The current or last known family name of the person",
      "type": "string"
    },
    "isEastern": {
      "description": "Whether the person is Eastern or Western (rendering of the full name and naming of the relatives",
      "type": "boolean",
      "default": false
    },
    "parents": {
      "description": "Immediate ancestors of the person, i.e. father and mother",
      "type": "array",
      "item": {
        "type": { "$dynamicRef": "#relative" }
      }
    },
    "spouse": {
      "description": "The ligated other person, e.g. husband, wife, mate, ...",
      "type": { "$dynamicRef": "#relative" }
    },
    "children": {
      "description": "The immediate offsprings, i.e. daughters, sons.",
      "type": "array",
      "item": {
        "type": { "$dynamicRef": "#relative" }
      }
    }
  },
  "required": [ "givenNames", "gender", "birthday", "familyName" ]
}

=== melli79/melli79.github.io/games/relatives/chinese.json
{
  "givenNames" : [ "我" ],
  "gender" : "female",
  "birthday" : {
    "year" : 1991
  },
  "familyName" : "家",
  "isEastern": true,
  "parents" : [ {
      "givenNames": [ "爸爸" ],
      "gender": "male",
      "birthday": {
        "year": 1965
      },
      "familyName": "家",
      "isEastern": true,
      "parents": [ {
        "givenNames": [ "爷爷" ],
        "gender": "male",
        "birthday": {
          "year": 1938
        },
        "familyName": "家",
        "isEastern": true,
        "children": [ {
          "givenNames": [ "姑姑" ],
          "gender": "female",
          "birthday": {
            "year": 1960
          },
          "familyName": "林",
          "isEastern": true,
          "spouse": {
            "givenNames": [ "姑父" ],
            "gender": "male",
            "birthday": {
              "year": 1961
            },
            "familyName": "深",
            "isEastern": true
          },
          "children": [ {
            "givenNames": [ "表哥" ],
            "gender": "male",
            "birthday": {
              "year": 1988
            },
            "familyName": "深",
            "isEastern": true,
            "spouse": {
              "givenNames": [ "表嫂" ],
              "gender": "female",
              "birthday": {
                "year": 1989
              },
              "familyName": "",
              "isEastern": true
            },
            "children": [ {
              "givenNames": [],
              "gender": "male",
              "birthday": {
                "year": 2015
              },
              "familyName": "深",
              "isEastern": true
            }, {
              "givenNames": [],
              "gender": "female",
              "birthday": {
                "year": 2017
              },
              "familyName": "深",
              "isEastern": true
            } ]
          } ]
        }, {
          "givenNames": [ "姑妈" ],
          "gender": "female",
          "birthday": {
            "year": 1967
          },
          "familyName": "林",
          "isEastern": true,
          "spouse": {
            "givenNames": [ "姑丈" ],
            "gender": "male",
            "birthday": {
              "year": 1966
            },
            "familyName": "陈",
            "isEastern": true
          },
          "children": [ {
            "givenNames": [ "表哥" ],
            "gender": "male",
            "birthday": {
              "year": 1989
            },
            "familyName": "陈",
            "isEastern": true
          }, {
            "givenNames": [ "表弟" ],
            "gender": "male",
            "birthday": {
              "year": 1996
            },
            "familyName": "陈",
            "isEastern": true,
            "spouse": {
              "givenNames": [ "表嫂" ],
              "gender": "female",
              "birthday": {
                "year": 1997
              },
              "familyName": ""
            },
            "children": [ {
              "givenNames": [ "？" ],
              "gender": "male",
              "birthday": {
                "year": 2019
              },
              "familyName": "陈",
              "isEastern": true
            } ]
          } ]
        }, {
          "givenNames": [ "伯伯" ],
          "gender": "male",
          "birthday": {
            "year": 1963
          },
          "familyName": "林",
          "isEastern": true,
          "spouse": {
            "givenNames": [ "伯母" ],
            "gender": "female",
            "birthday": {
              "year": 1964
            },
            "familyName": "沈",
            "isEastern": true
          },
          "children": [ {
            "givenNames": [ "堂哥" ],
            "gender": "male",
            "birthday": {
              "year": 1990
            },
            "familyName": "林",
            "isEastern": true,
            "spouse": {
              "givenNames": [ "堂嫂" ],
              "gender": "female",
              "birthday": {
                "year": 1991
              },
              "familyName": "",
              "isEastern": true
            },
            "children": [ {
              "givenNames": [],
              "gender": "male",
              "birthday": {
                "year": 2018
              },
              "familyName": "林",
              "isEastern": true
            } ]
          }, {
            "givenNames": [ "堂弟" ],
            "gender": "male",
            "birthday": {
              "year": 1992
            },
            "familyName": "林",
            "isEastern": true,
            "spouse": {
              "givenNames": [ "堂嫂" ],
              "gender": "female",
              "birthday": {
                "year": 1993
              },
              "familyName": "",
              "isEastern": true
            },
            "children": [ {
              "givenNames": [],
              "gender": "male",
              "birthday": {
                "year": 2020
              },
              "familyName": "林",
              "isEastern": true
            } ]
          } ]
        }, {
            "givenNames": [ "叔叔" ],
            "gender": "male",
            "birthday": {
              "year": 1968
            },
            "familyName": "林",
            "isEastern": true,
            "spouse": {
              "givenNames": [ "婶婶" ],
              "gender": "female",
              "birthday": {
                "year": 1969
              },
              "familyName": "沈",
              "isEastern": true
            },
            "children": [ {
              "givenNames": [ "表妹" ],
              "gender": "female",
              "birthday": {
                "year": 1992
              },
              "familyName": "林",
              "isEastern": true,
              "spouse": {
                "givenNames": [ "表妹夫" ],
                "gender": "male",
                "birthday": {
                  "year": 1991
                },
                "isEastern": true,
                "familyName": ""
              },
              "children": [ {
                "givenNames": [],
                "gender": "male",
                "birthday": {
                  "year": 2018
                },
                "familyName": "林",
                "isEastern": true
              } ]
            }, {
              "givenNames": [ "表弟" ],
              "gender": "male",
              "birthday": {
                "year": 1994
              },
              "familyName": "林",
              "isEastern": true,
              "spouse": {
                "givenNames": [ "表嫂" ],
                "gender": "female",
                "birthday": {
                  "year": 1995
                },
                "familyName": "",
                "isEastern": true
              },
              "children": [ {
                "givenNames": [],
                "gender": "male",
                "birthday": {
                  "year": 2020
                },
                "familyName": "林",
                "isEastern": true
              } ]
            } ]
          } ]
      }, {
          "givenNames": [ "奶奶" ],
          "gender": "female",
          "birthday": {
            "year": 1939
          },
          "familyName": "家",
          "isEastern": true,
          "parents": []
      } ],
    "children": [ {
      "givenNames" : [ "哥哥" ],
      "gender" : "male",
      "birthday" : {
        "year" : 1990
      },
      "familyName" : "家",
      "isEastern" : true,
      "spouse": {
        "givenNames": [ "嫂子" ],
        "gender": "female",
        "birthday": {
          "year": 1991
        },
        "familyName": "",
        "isEastern": true
      },
      "children" : [ ]
    }, {
      "givenNames" : [ "姐姐" ],
      "gender" : "female",
      "birthday" : {
        "year" : 1989
      },
      "familyName" : "家",
      "isEastern" : true,
      "spouse": {
        "givenNames": [ "姐夫" ],
        "gender": "male",
        "birthday": {
          "year": 1990
        },
        "familyName": "",
        "isEastern": true
      },
      "children" : [ {
        "givenNames": [ "外甥" ],
        "gender": "male",
        "birthday": {
          "year": 2020
        },
        "familyName": "",
        "isEastern": true
      }, {
        "givenNames": [ "外甥女" ],
        "gender": "female",
        "birthday": {
          "year": 2021
        },
        "familyName": "",
        "isEastern": true
      } ]
    }, {
      "givenNames" : [ "弟弟" ],
      "gender" : "male",
      "birthday" : {
        "year" : 1993
      },
      "familyName" : "家",
      "isEastern" : true,
      "spouse": {
        "givenNames": [ "弟妇" ],
        "gender": "female",
        "birthday": {
          "year": 1994
        },
        "familyName": "",
        "isEastern": true
      },
      "children" : [ ]
    }, {
      "givenNames" : [ "妹妹" ],
      "gender" : "female",
      "birthday" : {
        "year" : 1994
      },
      "familyName" : "家",
      "isEastern" : true,
      "spouse": {
        "givenNames": [ "妹夫" ],
        "gender": "male",
        "birthday": {
          "year": 1993
        },
        "familyName": "",
        "isEastern": true
      },
      "children" : [ ]
    } ]
    }, {
      "givenNames" : [ "妈妈" ],
      "gender" : "female",
      "birthday" : {
        "year" : 1966
      },
      "familyName" : "家",
      "isEastern": true,
      "parents": [ {
      "givenNames": [ "外公" ],
        "gender": "male",
        "birthday": {
          "year": 1937
        },
        "familyName": "大家庭",
        "isEastern": true,
        "children": [ {
          "givenNames": [ "阿姨" ],
          "gender": "female",
          "birthday": {
            "year": 1963
          },
          "familyName": "深",
          "isEastern": true,
          "spouse": {
            "givenNames": [ "姨丈" ],
            "gender": "male",
            "birthday": {
              "year": 1962
            },
